services:
  - type: web
    name: vigie-api
    runtime: docker
    plan: free
    dockerfilePath: ./src/Vigie.Api/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: PORT
        value: "10000"
      - key: AllowedOrigins
        value: https://minaseliman1.github.io
      - key: PublicAppUrl
        value: https://minaseliman1.github.io/vigie
      - key: Jwt__Key
        sync: false
      - key: ConnectionStrings__Vigie
        sync: false
