using Vigie.Domain;

namespace Vigie.Api.Contracts;

public sealed record LoginRequest(string Email, string Password);
public sealed record ChangePasswordRequest(string CurrentPassword, string NewPassword);
public sealed record PasswordResetRequest(string Email);
public sealed record PasswordResetConfirmRequest(string Token, string NewPassword);
public sealed record PasswordResetRequestResponse(string Message, string? ResetToken = null);
public sealed record NotificationResponse(Guid Id, string Type, string Title, string Body, string? ActionUrl, DateTimeOffset CreatedAtUtc, bool IsRead, DateTimeOffset? ReadAtUtc);
public sealed record AuditEntryResponse(Guid Id, string Action, string EntityType, Guid? EntityId, string? Details, string? ActorName, DateTimeOffset CreatedAtUtc);
public sealed record LoginResponse(string Token, DateTimeOffset ExpiresAtUtc, UserSummary User);
public sealed record RegisterOrganizationRequest(string OrganizationName, string Name, string Email, string Password);
public sealed record OrganizationResponse(Guid Id, string Name, string Slug, DateTimeOffset CreatedAtUtc);
public sealed record RegistrationResponse(LoginResponse Login, OrganizationResponse Organization);
public sealed record UserSummary(Guid Id, string Name, string Email, string Role, Guid OrganizationId, bool IsDemoAccount, Guid? SiteId = null, Guid? SectorId = null);
public sealed record InviteMemberRequest(string Email, string Name, string Role, Guid? SiteId = null, Guid? SectorId = null);
public sealed record InvitationResponse(Guid Id, string Email, string Name, string Role, string Status, DateTimeOffset ExpiresAtUtc, string? InviteToken, string? InviteLink, Guid? SiteId = null, Guid? SectorId = null);
public sealed record AcceptInvitationRequest(string Token, string Password, string? Name);
public sealed record SiteResponse(Guid Id, string Name, string Type, string TimeZoneId, OpeningSeason OpeningSeason, string Address = "", string Neighborhood = "", bool IsMunicipal = false, Guid? SectorId = null, string? SectorName = null);
public sealed record ShiftResponse(Guid Id, Guid SiteId, string SiteName, string SiteType, DateTimeOffset StartUtc, DateTimeOffset EndUtc, int RequiredLifeguards, IReadOnlyCollection<AssignmentResponse> Assignments, string Status = nameof(ShiftStatus.Open));
public sealed record AssignmentResponse(Guid Id, Guid ShiftId, Guid EmployeeId, string EmployeeName);
public sealed record CreateShiftRequest(Guid SiteId, DateTimeOffset StartUtc, DateTimeOffset EndUtc, int RequiredLifeguards);
public sealed record UpdateShiftRequest(DateTimeOffset StartUtc, DateTimeOffset EndUtc, int RequiredLifeguards);
public sealed record CreateSiteRequest(string Name, string Type, string TimeZoneId, int StartMonth, int StartDay, int EndMonth, int EndDay, string? Address = null, string? Neighborhood = null, bool IsMunicipal = false);
public sealed record AssignShiftRequest(Guid EmployeeId);
public sealed record CertificationResponse(Guid Id, Guid EmployeeId, string EmployeeName, string Type, DateOnly ExpiresOn, int DaysRemaining);
public sealed record CreateCertificationRequest(Guid EmployeeId, Guid CertificationTypeId, DateOnly ExpiresOn);
public sealed record SwapRequestResponse(Guid Id, Guid AssignmentId, Guid RequesterId, string RequesterName, Guid ReceiverId, string ReceiverName, string ShiftLabel, string Status, DateTimeOffset RequestedAtUtc);
public sealed record CreateSwapRequest(Guid AssignmentId, Guid ReceiverId);
public sealed record DashboardResponse(int UpcomingShifts, int PendingSwapRequests, int CertificationAlerts, IReadOnlyCollection<CertificationResponse> CertificationWarnings);
public sealed record AvailabilityRequest(DateOnly Date, bool IsAvailable, string? Note);
public sealed record AvailabilityResponse(Guid Id, Guid EmployeeId, DateOnly Date, bool IsAvailable, string? Note);
public sealed record CreateSectorRequest(string Name, string Code);
public sealed record UpdateSectorRequest(string Name, string Code, bool IsActive = true);
public sealed record SectorResponse(Guid Id, Guid OrganizationId, string Name, string Code, bool IsActive, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc);
public sealed record CreateMembershipRequest(Guid EmployeeId, string Role, Guid? SiteId = null, Guid? SectorId = null);
public sealed record UpdateMembershipRequest(string? Role = null, Guid? SiteId = null, Guid? SectorId = null, bool? IsActive = null, int? ExpectedVersion = null);
public sealed record MembershipResponse(Guid Id, Guid EmployeeId, string EmployeeName, string Email, string Role, Guid OrganizationId, Guid? SiteId, string? SiteName, Guid? SectorId, string? SectorName, bool IsActive, int Version, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc);
